# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12mY_YIi89Zwl4AhK7P0HyjWSsDFvpVZi
"""

!pip install PyMySQL

import pymysql
import pandas as pd
import datetime

blogdb = pymysql.connect(host='blogdb.cm2yxwfja9ii.ap-northeast-2.rds.amazonaws.com',
                      user='admin',
                      password='', ##비밀번호 입력
                      database='blogdb',
                      charset='utf8',
                      port=3306)

cursor =blogdb.cursor(pymysql.cursors.DictCursor)

sql = "SELECT * FROM `blog`;"
cursor.execute(sql)
result = cursor.fetchall()

sql = '''INSERT INTO `blog` (url, content, score, keywords,created_date)
    VALUES ('https://blog.naver.com/happybobbob/223171747178', '구로맛집', '1','닭갈비',now());'''

cursor.execute(sql)
blogdb.commit()

sql = '''SELECT * FROM `blog` WHERE 'url' != 'https://blog.naver.com/happybobbob/223171747178';'''

cursor.execute(sql)
result = cursor.fetchall()
result = pd.DataFrame(result)
result

query = '''DELETE FROM 'blog' WHERE created_date IS NULL'''
cursor.execute(query)
blogdb.commit()



sample_df = pd.read_csv('TEST_DATA(Sample_Data).csv')

sample_df

cursor =db1.cursor(pymysql.cursors.DictCursor)

sql = '''INSERT INTO `blog` (url, content, score, keywords, created_date)
    VALUES ('https://blog.naver.com/tlsehdgh4162/223057082857', '구로맛집', '1','곱창','2023.08.15');'''

mycursor.execute(sql)
myresult = mycursor.fetchall()
myresult = pd.DataFrame(result)
myresult

result = pd.DataFrame(myresult, index=[0])
result



